In [33]:
import pandas as pd
raw = pd.read_csv("/Users/ethan/Documents/GitHub/ExPsyLing/experiments/masked_prime/data/combined_data.csv")

In [34]:
#raw.head(50)

In [4]:
#list(raw)

In [5]:
raw['response'].unique()

array([nan, 'm', 'n'], dtype=object)

In [41]:
# make a list of the columns we want
cols = ['participant_id', 'sender', 'duration', 'prime', 'target', 'condition', 'soa_condition', 'congruence', 'correct', 'response', 'correct_response']

In [42]:
df = raw[cols]

In [43]:
df = df[df['sender'] == 'target']

In [44]:
df

,participant_id,sender,duration,prime,target,condition,soa_condition,congruence,correct,response,correct_response
13,51,target,843.38,snjghf,SHEEP,practice,practice,practice,True,n,n
19,51,target,593.04,iweonf,BOAT,practice,practice,practice,True,m,m
25,51,target,559.18,nvoiuh,HOUSE,practice,practice,practice,True,m,m
31,51,target,653.76,abjdhjs,HORSE,practice,practice,practice,True,n,n
40,51,target,520.14,roof,PIANO,Inc_Synth_Synth,long,incongruent,True,m,m
...,...,...,...,...,...,...,...,...,...,...,...
15606,69,target,699.20,belt,BELT,Con_Synth,short,congruent,True,m,m
15612,69,target,580.20,daisy,DAISY,Con_Nat,short,congruent,True,n,n
15618,69,target,577.90,peach,SHED,Inc_Nat_Synth,short,incongruent,True,m,m
15624,69,target,661.10,rake,HUSKY,Inc_Synth_Nat,short,incongruent,True,n,n
15630,69,target,709.20,fern,PETAL,Inc_Nat_Nat,short,incongruent,True,n,n

In [45]:
df = raw[cols]
df = df[df['sender'] == 'target']
df = df[df['condition'] != 'practice']
df = df.drop(columns = ['sender'])

In [46]:
df

,participant_id,duration,prime,target,condition,soa_condition,congruence,correct,response,correct_response
40,51,520.14,roof,PIANO,Inc_Synth_Synth,long,incongruent,True,m,m
47,51,640.66,sheep,BULL,Inc_Nat_Nat,long,incongruent,False,n,m
54,51,597.74,fort,GOAT,Inc_Synth_Nat,long,incongruent,True,n,n
61,51,495.68,pear,PEAR,Con_Nat,long,congruent,True,n,n
68,51,556.86,olive,MOTOR,Inc_Nat_Synth,long,incongruent,True,m,m
...,...,...,...,...,...,...,...,...,...,...
15606,69,699.20,belt,BELT,Con_Synth,short,congruent,True,m,m
15612,69,580.20,daisy,DAISY,Con_Nat,short,congruent,True,n,n
15618,69,577.90,peach,SHED,Inc_Nat_Synth,short,incongruent,True,m,m
15624,69,661.10,rake,HUSKY,Inc_Synth_Nat,short,incongruent,True,n,n
15630,69,709.20,fern,PETAL,Inc_Nat_Nat,short,incongruent,True,n,n

In [ ]:



df.loc[df['target'] == 'BULL', 'correct_response'] = 'n'

#df['accuracy'] = df['response'] == df['correct_response']

In [40]:
df

,participant_id,duration,prime,target,condition,soa_condition,congruence,response,correct_response,accuracy
40,51,520.14,roof,PIANO,Inc_Synth_Synth,long,incongruent,m,m,True
47,51,640.66,sheep,BULL,Inc_Nat_Nat,long,incongruent,n,n,True
54,51,597.74,fort,GOAT,Inc_Synth_Nat,long,incongruent,n,n,True
61,51,495.68,pear,PEAR,Con_Nat,long,congruent,n,n,True
68,51,556.86,olive,MOTOR,Inc_Nat_Synth,long,incongruent,m,m,True
...,...,...,...,...,...,...,...,...,...,...
15606,69,699.20,belt,BELT,Con_Synth,short,congruent,m,m,True
15612,69,580.20,daisy,DAISY,Con_Nat,short,congruent,n,n,True
15618,69,577.90,peach,SHED,Inc_Nat_Synth,short,incongruent,m,m,True
15624,69,661.10,rake,HUSKY,Inc_Synth_Nat,short,incongruent,n,n,True
15630,69,709.20,fern,PETAL,Inc_Nat_Nat,short,incongruent,n,n,True

In [31]:
df_e = df[df['participant_id'] == 46]
df_e = df_e.groupby(['soa_condition', 'congruence']).mean(['duration'])

In [32]:
df_e = df_e.reset_index()
df_e

Empty DataFrame
Columns: [soa_condition, congruence, participant_id, duration, accuracy]
Index: []

In [16]:
import seaborn as sns

In [47]:
#ax = sns.barplot(data = df_e, x = 'soa_condition', y = 'duration', hue = 'congruence')
#sns.move_legend(ax, "lower right")