In [2]:
import pandas as pd

In [49]:
a = [3, 4, 78, 6]
b = [43, 42, 178, 76]
c = [38, 45, 728, 46]

In [50]:
arla = pd.DataFrame({'a': a, 'b': b, 'c': c})

In [51]:
arla

    a    b    c
0   3   43   38
1   4   42   45
2  78  178  728
3   6   76   46

In [54]:
arla["row_mean"] = arla.mean(axis=1)

In [55]:
arla

    a    b    c    row_mean
0   3   43   38   28.000000
1   4   42   45   30.333333
2  78  178  728  328.000000
3   6   76   46   42.666667

In [57]:
df = pd.read_csv('/work/E2026/ExPsyLing/notebooks/Stroop-raw-over-the-years.csv')

In [58]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year
0             4.16        6.76          4.45         4.65  2015
1             4.35        7.73          4.78         4.46  2015
2             3.60        7.00          4.00         3.50  2015
3             3.90        9.03          4.60         6.30  2015
4             4.22        9.98          6.83         6.24  2015
..             ...         ...           ...          ...   ...
200           4.77       10.00          5.66         6.24  2025
201           4.61       12.80          6.87         9.55  2025
202           4.79       10.72          5.64         7.25  2025
203           4.41        8.87          6.70         6.70  2025
204           5.50        9.80          6.20        21.70  2025

[205 rows x 5 columns]

In [64]:
df = df.drop(['Year'],axis=1)
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int   meanRT
0             4.16        6.76          4.45         4.65  407.004
1             4.35        7.73          4.78         4.46  407.264
2             3.60        7.00          4.00         3.50  406.620
3             3.90        9.03          4.60         6.30  407.766
4             4.22        9.98          6.83         6.24  408.454
..             ...         ...           ...          ...      ...
200           4.77       10.00          5.66         6.24  410.334
201           4.61       12.80          6.87         9.55  411.766
202           4.79       10.72          5.64         7.25  410.680
203           4.41        8.87          6.70         6.70  410.336
204           5.50        9.80          6.20        21.70  413.640

[205 rows x 5 columns]

In [65]:
df['MeanRT'] = df.mean(axis=1)

In [66]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int   meanRT   MeanRT
0             4.16        6.76          4.45         4.65  407.004  85.4048
1             4.35        7.73          4.78         4.46  407.264  85.7168
2             3.60        7.00          4.00         3.50  406.620  84.9440
3             3.90        9.03          4.60         6.30  407.766  86.3192
4             4.22        9.98          6.83         6.24  408.454  87.1448
..             ...         ...           ...          ...      ...      ...
200           4.77       10.00          5.66         6.24  410.334  87.4008
201           4.61       12.80          6.87         9.55  411.766  89.1192
202           4.79       10.72          5.64         7.25  410.680  87.8160
203           4.41        8.87          6.70         6.70  410.336  87.4032
204           5.50        9.80          6.20        21.70  413.640  91.3680

[205 rows x 6 columns]